### ISSUE TITLE
Visual does not show data

### ISSUE THREAD

**Issue by LinqLover** [DiaAzul/powerBI-visual-Heatmap3#3]
Hi @DiaAzul, this visual looks very cool from what I can see in the readme! Unfortunately, I cannot get it run in my report, it only shows an empty table.

I checked out the latest master commit, built the visual using `npm run install && npm run package`, and imported the `.pbiviz` file into my report in PBI Desktop (version October 2020).

This is the visual and its attached data as shown by the "display as table option in the visual menu":

![image](https://user-images.githubusercontent.com/38782922/97858055-e12c9b80-1cfe-11eb-8f48-14929f213443.png)

Do you see any problem with the data, or is this a bug in the visual (it might be incompatible with any changes on the PBI side)? I'd greatly appreciate your reaction to this issue, especially since @Microsoft's official [Table Heatmap visual](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104380818?src=office&tab=Reviews) is broken, too, and this visualization would be very helpful for me.

**Comment by DiaAzul** [comment]
Thanks for your comment. Since the visualisation was developed Microsoft has updated the PowerBI API. I haven't had an opportunity to revisit the visualisations to work out what is required to bring them up to date. Microsoft has, rather unhelpfully, removed the page which detailed the changes that they had made to the API. As the Table Heatmap visual was developed at around the same time as my visual, it is likely that it wasn't updated either.

Your data looks OK, I am assuming that weekday and hour are two separate columns - it isn't clear from the graphic. You may want to use the sample data in the sample data folder to check whether the visual works or whether it is your data.

**Comment by LinqLover** [comment]
Ah, thank you a lot! The sample data use a string of `{'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Bank Holiday'}` (not localized) whereas I was passing weekday numbers to the column. When transforming the numbers in my reports to English names (a bit tricky because I'm using German localization settings, but no matter), it works! 🎉
